# Generated by Django 3.0.2 on 2020-01-29 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0003_auto_20200128_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='начальный баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='валюта счета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('status', models.IntegerField(choices=[(0, 'Penging'), (1, 'EXECUTED'), (2, 'FAILED')], verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_transactions', to='transactions.Account', verbose_name='Отправитель')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Account', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
