# Generated by Django 3.0.2 on 2020-01-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20200128_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foreignexchangerate',
            unique_together={('base', 'rate_currency')},
        ),
    ]
